#!/usr/bin/env python3
"""
Bundles the game into a single Luau chunk that can run outside Roblox.

Each module body becomes a closure taking its own `script`, so Roblox-style
`require(script.Parent.Thing)` resolves against a mock instance tree instead of
the filesystem. Engine globals are shadowed by locals from the mock prelude, so
the game source itself is used verbatim - no edits, no stubs injected.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
TEST = ROOT / "test"

# folder -> instance tree location
LAYOUT = [
    ("shared", "Shared"),
    ("server", "Server"),
    ("client", "Client"),
]


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


def collect():
    """Returns (modules, entries) keyed by 'folder/Name'."""
    modules = {}
    entries = {}
    for folder, _ in LAYOUT:
        directory = SRC / folder
        for path in sorted(directory.glob("*.luau")):
            stem = path.stem
            if stem.startswith("init."):
                entries[folder] = read(path)
            else:
                modules[f"{folder}/{stem}"] = read(path)
    return modules, entries


def main() -> int:
    modules, entries = collect()

    out = []
    out.append("--!nonstrict")
    out.append("-- GENERATED by test/bundle.py - do not edit")
    out.append("")

    # The mock environment, inlined as an immediately-invoked closure.
    out.append("local Mock = (function()")
    out.append(read(TEST / "prelude.luau"))
    out.append("end)()")
    out.append("")

    # Shadow the engine globals the game code expects.
    out.append("local __env = Mock.env")
    for name in (
        "game workspace Instance Vector3 Vector2 CFrame Color3 UDim UDim2 "
        "Enum Random task os typeof warn PhysicalProperties TweenInfo RaycastParams"
    ).split():
        out.append(f"local {name} = __env.{name}")
    out.append("")

    # Module registry.
    out.append("local __loaders = {}")
    out.append("local __cache = {}")
    out.append("local __loaderOf = {}")
    out.append("")
    out.append("local function require(target)")
    out.append("\tif __cache[target] ~= nil then return __cache[target] end")
    out.append("\tlocal loader = __loaderOf[target]")
    out.append('\tif not loader then error("mock require: no module for " .. tostring(target), 2) end')
    out.append("\tlocal result = loader(target)")
    out.append("\t__cache[target] = result")
    out.append("\treturn result")
    out.append("end")
    out.append("")

    for key, source in modules.items():
        out.append(f"__loaders[{key!r}] = function(script)")
        out.append(source)
        out.append("end")
        out.append("")

    for folder, source in entries.items():
        out.append(f"__loaders[{folder + '/__entry'!r}] = function(script)")
        out.append(source)
        out.append("end")
        out.append("")

    # Instance tree that mirrors default.project.json.
    out.append(read(TEST / "tree.luau"))
    out.append("")
    out.append(read(TEST / "smoke.luau"))

    target = ROOT / "test" / "build" / "smoke.luau"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"bundled {len(modules)} modules + {len(entries)} entry points -> {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
